export { Wrapper } from 'src/components/Wrapper/Wrapper';
export { Secret } from 'src/componentsSecret/Secret';
export { NotFound } from 'src/componentsNotFound/NotFound';
export { MovieSearchForm } from 'src/componentsMovieSearchForm/MovieSearchForm';
export { MovieDetails } from 'src/componentsMovieDetails/MovieDetails'
export { MovieCard } from 'src/componentsMovieCard/MovieCard';
export { Home } from 'src/componentsHome/Home';
export { Header } from 'src/componentsHeader/Header';
export { Gallery } from 'src/componentsGallery/Gallery';
export { Footer } from 'src/componentsFooter/Footer';
