export { Wrapper } from './Wrapper/Wrapper';
export { Secret } from './Secret/Secret';
export { NotFound } from './NotFound/NotFound';
export { MovieSearchForm } from './MovieSearchForm/MovieSearchForm';
export { MovieDetails } from './MovieDetails/MovieDetails'
export { MovieCard } from './MovieCard/MovieCard';
export { Home } from './Home/Home';
export { Header } from './Header/Header';
export { Gallery } from './Gallery/Gallery';
export { Footer } from './Footer/Footer';
